### ISSUE TITLE
Whitelist URLs from sending to sleep

### ISSUE THREAD

**Issue by moritzadler** [343max/TabHibernation#2]
Exclude certain URLs from "sending to sleep" by whitelisting them.
e.g. 
As a user, 
if I'm loading a YouTube video in background while working in another tab,
I don't want to send the YouTube tab to sleep and lose the semi-loaded video.

**Comment by HorayNarea** [comment]
implemented in 683458a, you can now whitelist URLs via the options-page

leaving this open because the amount of URLs is limited (by the chrome.storage.sync API) to 8192 bytes (which is about 200-300 URLs, depending how long they are)

by using the local storage we could have unlimited amounts of URLs but they wouldn't get synced across devices
